"""Digit-patch CNN for detecting broken/missing LCD segments.

No human labels needed: synthetic defects are generated by erasing random
segments from good-bank patches using the known _SEG_BOXES positions.

Architecture: lightweight ConvNet (< 200K params) that runs in <1ms per patch
on MPS/CPU. Trained once via scripts/train_digit_cnn.py, loaded at inference.
"""
from __future__ import annotations

import random
from pathlib import Path
from typing import Sequence

import cv2
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F

PATCH_SIZE = 64   # all digit patches resized to this before CNN
DEVICE = (
    "mps" if torch.backends.mps.is_available()
    else "cuda" if torch.cuda.is_available()
    else "cpu"
)

# Segment boxes (same as segments.py) — used to synthesise defects
_SEG_BOXES = {
    "a": (0.27, 0.09, 0.52, 0.16),
    "b": (0.72, 0.26, 0.20, 0.26),
    "c": (0.72, 0.60, 0.20, 0.27),
    "d": (0.27, 0.83, 0.52, 0.14),
    "e": (0.27, 0.60, 0.20, 0.27),
    "f": (0.27, 0.26, 0.20, 0.26),
    "g": (0.27, 0.46, 0.52, 0.14),
}


# ── Model ─────────────────────────────────────────────────────────────────────

class DigitCNN(nn.Module):
    """Binary classifier: 0 = intact, 1 = defective."""

    def __init__(self):
        super().__init__()
        self.features = nn.Sequential(
            nn.Conv2d(1, 16, 3, padding=1), nn.BatchNorm2d(16), nn.ReLU(),
            nn.MaxPool2d(2),                                    # → 32
            nn.Conv2d(16, 32, 3, padding=1), nn.BatchNorm2d(32), nn.ReLU(),
            nn.MaxPool2d(2),                                    # → 16
            nn.Conv2d(32, 64, 3, padding=1), nn.BatchNorm2d(64), nn.ReLU(),
            nn.MaxPool2d(2),                                    # → 8
            nn.Conv2d(64, 64, 3, padding=1), nn.BatchNorm2d(64), nn.ReLU(),
            nn.AdaptiveAvgPool2d(4),                            # → 4×4
        )
        self.classifier = nn.Sequential(
            nn.Flatten(),
            nn.Linear(64 * 4 * 4, 128), nn.ReLU(), nn.Dropout(0.3),
            nn.Linear(128, 2),
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.classifier(self.features(x))


# ── Patch preprocessing ───────────────────────────────────────────────────────

def crop_patch(image_gray: np.ndarray, bbox: tuple[int, int, int, int]) -> np.ndarray:
    """Crop and resize a digit patch to PATCH_SIZE×PATCH_SIZE."""
    x, y, w, h = bbox
    patch = image_gray[y:y + h, x:x + w]
    if patch.size == 0:
        return np.zeros((PATCH_SIZE, PATCH_SIZE), dtype=np.uint8)
    return cv2.resize(patch, (PATCH_SIZE, PATCH_SIZE), interpolation=cv2.INTER_LINEAR)


def patch_to_tensor(patch: np.ndarray) -> torch.Tensor:
    t = torch.from_numpy(patch.astype(np.float32) / 255.0).unsqueeze(0).unsqueeze(0)
    return t.to(DEVICE)


# ── Synthetic defect generation ───────────────────────────────────────────────

def _erase_segment(patch: np.ndarray, seg: str) -> np.ndarray:
    """Erase one segment from a digit patch by filling with local background."""
    H, W = patch.shape[:2]
    sx, sy, sw, sh = _SEG_BOXES[seg]
    x = int(sx * W);  y = int(sy * H)
    w = max(1, int(sw * W));  h = max(1, int(sh * H))
    out = patch.copy()
    # Fill with median of surrounding border (approximates LCD background)
    border = []
    for dy in range(-3, h + 3):
        for dx in range(-3, w + 3):
            if dy < 0 or dy >= h or dx < 0 or dx >= w:
                py, px = y + dy, x + dx
                if 0 <= py < H and 0 <= px < W:
                    border.append(int(patch[py, px]))
    fill = int(np.median(border)) if border else 200
    out[y:y + h, x:x + w] = fill
    return out


def make_defective(patch: np.ndarray, n_segs: int | None = None) -> np.ndarray:
    """Erase 1–3 random segments from a good patch to simulate a defect."""
    segs = list(_SEG_BOXES.keys())
    k = n_segs if n_segs is not None else random.randint(1, 3)
    k = min(k, len(segs))
    chosen = random.sample(segs, k)
    out = patch
    for seg in chosen:
        out = _erase_segment(out, seg)
    return out


# ── Dataset helper (used by training script) ─────────────────────────────────

class DigitPatchDataset(torch.utils.data.Dataset):
    """In-memory dataset of (patch_tensor, label) pairs."""

    def __init__(self, patches: list[np.ndarray], labels: list[int],
                 augment: bool = False):
        self.patches = patches
        self.labels  = labels
        self.augment = augment

    def __len__(self) -> int:
        return len(self.patches)

    def __getitem__(self, idx: int):
        patch = self.patches[idx].copy()
        if self.augment:
            # mild brightness jitter
            delta = random.randint(-20, 20)
            patch = np.clip(patch.astype(np.int32) + delta, 0, 255).astype(np.uint8)
        t = torch.from_numpy(patch.astype(np.float32) / 255.0).unsqueeze(0)
        return t, torch.tensor(self.labels[idx], dtype=torch.long)


# ── Inference ─────────────────────────────────────────────────────────────────

class DigitCNNScorer:
    """Loads a trained DigitCNN and scores digit patches."""

    def __init__(self, model_path: str | Path):
        self.model = DigitCNN().to(DEVICE)
        state = torch.load(str(model_path), map_location=DEVICE, weights_only=True)
        self.model.load_state_dict(state)
        self.model.eval()

    def score(self, patch: np.ndarray) -> float:
        """Return P(defective) ∈ [0, 1]."""
        resized = cv2.resize(patch, (PATCH_SIZE, PATCH_SIZE), interpolation=cv2.INTER_LINEAR)
        with torch.no_grad():
            t = torch.from_numpy(resized.astype(np.float32) / 255.0).unsqueeze(0).unsqueeze(0).to(DEVICE)
            logits = self.model(t)
            return float(F.softmax(logits, dim=1)[0, 1].item())

    def is_defective(self, patch: np.ndarray, threshold: float = 0.5) -> bool:
        return self.score(patch) >= threshold
